# Configuration file to set paths and other hyper-parameters while processing a 3D scene
# Set the data paths as follows
# 'AreaName' is the scene /directory containing images set and sparse reconstruction by colmap
# 'dataset_path' is the root directory that may contain several scenes
# Segmentation_path is the directory containing instance segmentations of either one scene or even for all the scenes of a city,

# for example if you have one scene from a city, organise as follows:
#---Genoa_porto_antico
#   |--images
#   |--inst_seg
#   |--sparse_recons

data:
  AreaName: 'Genoa_porto_antico'
  dataset_path: '/media/javedahmad/Data/mapillary/'
  segmentation_path: '/media/javedahmad/Data/mapillary/'

## Threshold Values that may slightly vary for any scene, but in our case same values works
Scaning:
  method: dbscan   #density based scanning
  eps: 0.05
  min_3dpoints: 10  #it is the number of points on Average on objects, it helps in DBScanning

SOR_parameters:   # statistical outlier removal for discarding noisy points in the scene
  nb_neighbors: 10
  std_ratio: 0.8

# If you want to have 2D instance segmentation on images while being processed.
# Note that it will slow the process, better to create while you already have run the code.
Image_Segmentations:
  creat_folder: True
  Write_Seg_in_texts: False
  Write_Seg_on_images: False

# You can select different options to have different way of matched detections either separatly or at one place
MatchedDetection:
  Write_MatchedDetection_on_images : True
  Write_MatchedDetection_on_images_inOneFolder : False
  Write_MatchedDetection_on_images_inSeparateFolder : True
  WriteAssociationGraph: True
  SeparateFolders: True
  Plyfiles: True
  intersection_threshold: 0.65
  DiscardObjectsWith_Views: 2

miscellaneous:
  cam_scale: 0.10  # Camera size in the scene while visualizing in Open3D window


